# ▀█▀ ░█▀▀█ ░█▀▀▀ ░█▀▀█ ░█▀▀▀█ ░█▀▀█ ░█▀▀▀
# ░█─ ░█─── ░█▀▀▀ ░█─── ░█──░█ ░█▄▄▀ ░█▀▀▀
# ▄█▄ ░█▄▄█ ░█▄▄▄ ░█▄▄█ ░█▄▄▄█ ░█─░█ ░█▄▄▄

# Message of the day
motd:
  - '&cWelcome %player_name%!'
  - 'How are you?'


# Disables commands
# if you for example want to disable "/plugins" you need to disable pl, plugins, bukkit:pl, bukkit:plugins
disabled-commands:
  - pl
  - plugins
  - bukkit:pl
  - bukkit:plugins
  - bukkit:ver
  - bukkit:version
  - ver
  - version

