name: IceCore
version: ${project.version}
main: me.iceman3920.icecore.IceCore
api-version: 1.17
authors: [ iceman3920 ]
softdepend:
  - PlaceholderAPI
  - DiscordSRV

commands:
  gamemode:
    aliases: gm
    permission: icecore.gamemode.*

  gmc:
    permission: icecore.gamemode.creative

  gms:
    permission: icecore.gamemode.survival
  gma:
    permission: icecore.gamemode.adventure
  gmsp:
    permission: icecore.gamemode.spectator

  feed:
    permission: icecore.feed

  heal:
    permission: icecore.heal

  fly:
    permission: icecore.fly

  clearchat:
    permission: icecore.clear.chat
    aliases:
      - cc

  godmode:
    permission: icecore.godmode
    aliases:
      - god

  shutdown:
    permission: icecore.shutdown
    aliases:
      - stop

  vanish:
    aliases:
      - v
      - van
    permission: icecore.vanish

  staffchat:
    aliases:
      - sc
      - staffc
    permission: icecore.staffchat

  oretracker:
    aliases:
      - ot
    permission: icecore.oretracker

permissions:
  icecore.*:
    default: op




